.TH "SMPLSharp.Objects.SmplQueueElement" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Objects.SmplQueueElement \- 
.PP
Элемент очереди  

.SH SYNOPSIS
.br
.PP
.SS "Свойства"

.in +1c
.ti -1c
.RI "virtual object \fBValue\fP\fC [get, set]\fP"
.br
.RI "\fIСодержимое элемента \fP"
.ti -1c
.RI "virtual int \fBPriority\fP\fC [get, set]\fP"
.br
.RI "\fIПриоритет элемента \fP"
.ti -1c
.RI "virtual int \fBTimeAdded\fP\fC [get, set]\fP"
.br
.RI "\fIВремя добавления в очередь \fP"
.in -1c
.SH "Подробное описание"
.PP 
Элемент очереди 


.PP
См\&. определение в файле SmplQueue\&.cs строка 260
.SH "Полный список свойств"
.PP 
.SS "virtual int SMPLSharp\&.Objects\&.SmplQueueElement\&.Priority\fC [get]\fP, \fC [set]\fP"

.PP
Приоритет элемента 
.PP
См\&. определение в файле SmplQueue\&.cs строка 280
.SS "virtual int SMPLSharp\&.Objects\&.SmplQueueElement\&.TimeAdded\fC [get]\fP, \fC [set]\fP"

.PP
Время добавления в очередь 
.PP
См\&. определение в файле SmplQueue\&.cs строка 290
.SS "virtual object SMPLSharp\&.Objects\&.SmplQueueElement\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Содержимое элемента 
.PP
См\&. определение в файле SmplQueue\&.cs строка 270

.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
