.TH "SMPLSharp.Utils.SmplReporter" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Utils.SmplReporter \- 
.PP
Give model statistic  

.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSmplReporter\fP (\fBSmplModel\fP model)"
.br
.RI "\fIКонструктор для \fBSmplReporter\fP \fP"
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "int \fBModelTime\fP\fC [get]\fP"
.br
.RI "\fIВремя моделирования \fP"
.ti -1c
.RI "List< \fBSmplRDeviceStatisic\fP > \fBDeviceStatistic\fP\fC [get]\fP"
.br
.RI "\fIИнформация о приборах \fP"
.ti -1c
.RI "List< \fBSmplRMultiDeviceStatisic\fP > \fBMultiDeviceStatistic\fP\fC [get]\fP"
.br
.RI "\fIИнформация о многоканальных приборах \fP"
.ti -1c
.RI "List< \fBSmplRQueueStatisic\fP > \fBQueueStatistic\fP\fC [get]\fP"
.br
.RI "\fIИнформация о очередях \fP"
.ti -1c
.RI "\fBSmplModel\fP \fBModel\fP\fC [get, set]\fP"
.br
.RI "\fIМодель, с которой связан прибор \fP"
.in -1c
.SH "Подробное описание"
.PP 
Give model statistic 


.PP
См\&. определение в файле SmplReporter\&.cs строка 162
.SH "Конструктор(ы)"
.PP 
.SS "SMPLSharp\&.Utils\&.SmplReporter\&.SmplReporter (\fBSmplModel\fPmodel)"

.PP
Конструктор для \fBSmplReporter\fP \fBАргументы:\fP
.RS 4
\fImodel\fP Модель
.RE
.PP

.PP
См\&. определение в файле SmplReporter\&.cs строка 265
.SH "Полный список свойств"
.PP 
.SS "List<\fBSmplRDeviceStatisic\fP> SMPLSharp\&.Utils\&.SmplReporter\&.DeviceStatistic\fC [get]\fP"

.PP
Информация о приборах 
.PP
См\&. определение в файле SmplReporter\&.cs строка 178
.SS "\fBSmplModel\fP SMPLSharp\&.Utils\&.SmplReporter\&.Model\fC [get]\fP, \fC [set]\fP"

.PP
Модель, с которой связан прибор 
.PP
См\&. определение в файле SmplReporter\&.cs строка 251
.SS "int SMPLSharp\&.Utils\&.SmplReporter\&.ModelTime\fC [get]\fP"

.PP
Время моделирования 
.PP
См\&. определение в файле SmplReporter\&.cs строка 170
.SS "List<\fBSmplRMultiDeviceStatisic\fP> SMPLSharp\&.Utils\&.SmplReporter\&.MultiDeviceStatistic\fC [get]\fP"

.PP
Информация о многоканальных приборах 
.PP
См\&. определение в файле SmplReporter\&.cs строка 201
.SS "List<\fBSmplRQueueStatisic\fP> SMPLSharp\&.Utils\&.SmplReporter\&.QueueStatistic\fC [get]\fP"

.PP
Информация о очередях 
.PP
См\&. определение в файле SmplReporter\&.cs строка 225

.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
