.TH "SMPLSharp.Utils.SmplRQueueStatisic" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Utils.SmplRQueueStatisic \- 
.PP
Статистика по очереди  

.SH SYNOPSIS
.br
.PP
.SS "Свойства"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIИмя \fP"
.ti -1c
.RI "double \fBAverageTimeWaiting\fP\fC [get, set]\fP"
.br
.RI "\fIСреднее время ожидания \fP"
.ti -1c
.RI "double \fBDispersalTimeWaiting\fP\fC [get, set]\fP"
.br
.RI "\fIРазброс времени ожидания \fP"
.ti -1c
.RI "double \fBAverageLength\fP\fC [get, set]\fP"
.br
.RI "\fIСредняя длина очереди \fP"
.ti -1c
.RI "int \fBMaxLength\fP\fC [get, set]\fP"
.br
.RI "\fIМаксимальная длина очереди \fP"
.ti -1c
.RI "int \fBTotalCount\fP\fC [get, set]\fP"
.br
.RI "\fIЧисло заявок, попавших в очередь \fP"
.in -1c
.SH "Подробное описание"
.PP 
Статистика по очереди 


.PP
См\&. определение в файле SmplReporter\&.cs строка 90
.SH "Полный список свойств"
.PP 
.SS "double SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.AverageLength\fC [get]\fP, \fC [set]\fP"

.PP
Средняя длина очереди 
.PP
См\&. определение в файле SmplReporter\&.cs строка 129
.SS "double SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.AverageTimeWaiting\fC [get]\fP, \fC [set]\fP"

.PP
Среднее время ожидания 
.PP
См\&. определение в файле SmplReporter\&.cs строка 109
.SS "double SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.DispersalTimeWaiting\fC [get]\fP, \fC [set]\fP"

.PP
Разброс времени ожидания 
.PP
См\&. определение в файле SmplReporter\&.cs строка 119
.SS "int SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.MaxLength\fC [get]\fP, \fC [set]\fP"

.PP
Максимальная длина очереди 
.PP
См\&. определение в файле SmplReporter\&.cs строка 139
.SS "string SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Имя 
.PP
См\&. определение в файле SmplReporter\&.cs строка 99
.SS "int SMPLSharp\&.Utils\&.SmplRQueueStatisic\&.TotalCount\fC [get]\fP, \fC [set]\fP"

.PP
Число заявок, попавших в очередь 
.PP
См\&. определение в файле SmplReporter\&.cs строка 150

.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
