.TH "SMPLSharp.Objects" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Objects \- 
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBSmplDevice\fP"
.br
.RI "\fIEquipment or facility Typically represents some work-performing resource of system being modeled The Interconnection of facilities is not explicit, but can be determined by the model’s routing of tokens between facilities \fP"
.ti -1c
.RI "class \fBSmplEvent\fP"
.br
.RI "\fIModel's event A change of state of any system entity, active or passive Can be, for example, Arrival of task or Computing completion \fP"
.ti -1c
.RI "class \fBSmplMultiDevice\fP"
.br
.RI "\fIEquipment or facility Typically represents some work-performing resource of system being modeled The Interconnection of facilities is not explicit, but can be determined by the model’s routing of tokens between facilities \fP"
.ti -1c
.RI "class \fBSmplQueue\fP"
.br
.RI "\fIОчередь\&. Represents place where tokens are waiting when equipment is busy \fP"
.ti -1c
.RI "class \fBSmplQueueElement\fP"
.br
.RI "\fIЭлемент очереди \fP"
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
