.TH "SMPLSharp.Utils.SmplRDeviceStatisic" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Utils.SmplRDeviceStatisic \- 
.PP
Статистика по прибору  

.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBSMPLSharp\&.Utils\&.SmplRMultiDeviceStatisic\fP\&.
.SS "Свойства"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIИмя \fP"
.ti -1c
.RI "double \fBAverageTimeReserved\fP\fC [get, set]\fP"
.br
.RI "\fIСреднее время обслуживания заявки \fP"
.ti -1c
.RI "double \fBBusyIndex\fP\fC [get, set]\fP"
.br
.RI "\fIЗанятость прибора (0\&.\&.1) \fP"
.ti -1c
.RI "int \fBQueryCount\fP\fC [get, set]\fP"
.br
.RI "\fIКоличество обслужанных заявок \fP"
.in -1c
.SH "Подробное описание"
.PP 
Статистика по прибору 


.PP
См\&. определение в файле SmplReporter\&.cs строка 17
.SH "Полный список свойств"
.PP 
.SS "double SMPLSharp\&.Utils\&.SmplRDeviceStatisic\&.AverageTimeReserved\fC [get]\fP, \fC [set]\fP"

.PP
Среднее время обслуживания заявки 
.PP
См\&. определение в файле SmplReporter\&.cs строка 36
.SS "double SMPLSharp\&.Utils\&.SmplRDeviceStatisic\&.BusyIndex\fC [get]\fP, \fC [set]\fP"

.PP
Занятость прибора (0\&.\&.1) 
.PP
См\&. определение в файле SmplReporter\&.cs строка 46
.SS "string SMPLSharp\&.Utils\&.SmplRDeviceStatisic\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Имя 
.PP
См\&. определение в файле SmplReporter\&.cs строка 26
.SS "int SMPLSharp\&.Utils\&.SmplRDeviceStatisic\&.QueryCount\fC [get]\fP, \fC [set]\fP"

.PP
Количество обслужанных заявок 
.PP
См\&. определение в файле SmplReporter\&.cs строка 56

.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
