.TH "SMPLSharp" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp \- 
.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "package \fBObjects\fP"
.br
.ti -1c
.RI "package \fBUtils\fP"
.br
.in -1c
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBSmplModel\fP"
.br
.RI "\fISimulation model\&. Provides set of function for building event-based, discrete-event simulation model \fP"
.ti -1c
.RI "class \fBEventCausedEventArgs\fP"
.br
.RI "\fIEvent when model's event is caused \fP"
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "delegate void \fBEventCausedHandler\fP (object o, \fBEventCausedEventArgs\fP e)"
.br
.RI "\fIDelegate for EventCaused \fP"
.in -1c
.SH "Функции"
.PP 
.SS "delegate void SMPLSharp\&.EventCausedHandler (objecto, EventCausedEventArgse)"

.PP
Delegate for EventCaused \fBАргументы:\fP
.RS 4
\fIo\fP 
.br
\fIe\fP 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
