.TH "SMPLSharp.Utils" 3 "Пт 5 Апр 2013" "SMPLSharp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPLSharp.Utils \- 
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBSmplRandomGenerator\fP"
.br
.RI "\fIГенератор случайных чисел \fP"
.ti -1c
.RI "class \fBSmplRDeviceStatisic\fP"
.br
.RI "\fIСтатистика по прибору \fP"
.ti -1c
.RI "class \fBSmplRMultiDeviceStatisic\fP"
.br
.RI "\fIСтатистика по многоканальному прибору \fP"
.ti -1c
.RI "class \fBSmplRQueueStatisic\fP"
.br
.RI "\fIСтатистика по очереди \fP"
.ti -1c
.RI "class \fBSmplReporter\fP"
.br
.RI "\fIGive model statistic \fP"
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для SMPLSharp из исходного текста\&.
